/* tslint:disable */
/* eslint-disable */
/**
 * Explorer
 * Explorer API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EthBlockDto
 */
export interface EthBlockDto {
    /**
     * 
     * @type {string}
     * @memberof EthBlockDto
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof EthBlockDto
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof EthBlockDto
     */
    parentHash: string;
    /**
     * 
     * @type {string}
     * @memberof EthBlockDto
     */
    gasUsed: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EthBlockDto
     */
    transactions: Array<string>;
}

/**
 * Check if a given object implements the EthBlockDto interface.
 */
export function instanceOfEthBlockDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "hash" in value;
    isInstance = isInstance && "parentHash" in value;
    isInstance = isInstance && "gasUsed" in value;
    isInstance = isInstance && "transactions" in value;

    return isInstance;
}

export function EthBlockDtoFromJSON(json: any): EthBlockDto {
    return EthBlockDtoFromJSONTyped(json, false);
}

export function EthBlockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthBlockDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
        'hash': json['hash'],
        'parentHash': json['parentHash'],
        'gasUsed': json['gasUsed'],
        'transactions': json['transactions'],
    };
}

export function EthBlockDtoToJSON(value?: EthBlockDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'hash': value.hash,
        'parentHash': value.parentHash,
        'gasUsed': value.gasUsed,
        'transactions': value.transactions,
    };
}

